#
# Repository validation
#
name: Analyze
on:
- pull_request
jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Run PSRule analysis
      uses: Microsoft/ps-rule@v1.12.0
      with:
        modules: 'PSRule.Rules.MSFT.OSS'
        prerelease: true
